---
- name: Install Clickhouse
  tags: clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
- name: Install Vector
  tags: vector
  hosts: vector
  roles:
    - vector
- name: Install LightHouse
  tags: lighthouse
  hosts: lighthouse
  roles:
    - lighthouse
