---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 84.201.152.138
vector:
  hosts:
    vector-01:
      ansible_host: 84.201.152.138
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 84.201.152.138
